# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_entry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_entry.proto\x12\x0fwavesenterprise\"\x80\x01\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\tint_value\x18\n \x01(\x03\x42\x02\x30\x01H\x00\x12\x14\n\nbool_value\x18\x0b \x01(\x08H\x00\x12\x16\n\x0c\x62inary_value\x18\x0c \x01(\x0cH\x00\x12\x16\n\x0cstring_value\x18\r \x01(\tH\x00\x42\x07\n\x05valueB[\n(com.wavesenterprise.transaction.protobufP\x01Z\x1bwavesenterprise.com/weproto\xaa\x02\x0fWavesEnterpriseb\x06proto3')



_DATAENTRY = DESCRIPTOR.message_types_by_name['DataEntry']
DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
  'DESCRIPTOR' : _DATAENTRY,
  '__module__' : 'data_entry_pb2'
  # @@protoc_insertion_point(class_scope:wavesenterprise.DataEntry)
  })
_sym_db.RegisterMessage(DataEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(com.wavesenterprise.transaction.protobufP\001Z\033wavesenterprise.com/weproto\252\002\017WavesEnterprise'
  _DATAENTRY.fields_by_name['int_value']._options = None
  _DATAENTRY.fields_by_name['int_value']._serialized_options = b'0\001'
  _DATAENTRY._serialized_start=38
  _DATAENTRY._serialized_end=166
# @@protoc_insertion_point(module_scope)
